#!/bin/bash

OD=`pwd`;
MO=$1;

function launch() {
	sleep $1;
	[ -e ${OD}/ipfs_repo/api ] && [ -e ${OD}/ipfs_repo/repo.lock ] && return 0 || launch $1;
}

rm -f ${OD}/Optract.LOCK;

if [ ${MO:-daemon} == "console" ]; then
   exec $OD/bin/node $OD/lib/console.js;
elif [ ${MO:-daemon} == "devConsole" ]; then
  (
    export IPFS_PATH="${OD}/ipfs_repo";
    [ -e ${OD}/ipfs_repo/config ] && echo "ipfs repo ready" || ${OD}/bin/ipfs init && \
    rm -f ${OD}/ipfs_repo/api ${OD}/ipfs_repo/repo.lock && ./run_ipfs.py daemon &
  )

  sed "s|__OPTRACT_INSTALL__|${OD}|g" ./dapps/config.json.dist > ./dapps/config.json && \
  rm -fr ${OD}/node_modules && ${OD}/bin/asar extract ${OD}/node_modules.asar ${OD}/node_modules && \
  echo -e "!!!!!\nNOTE: devConsole requires you turn off wsrpc in config.json ...\n!!!!!" && \
  launch 0.01 && ${OD}/bin/node ${OD}/lib/daemon.js && ./run_ipfs.py kill || ./run_ipfs.py kill;
  exit 0;
elif [ ${MO:-daemon} == "daemon" ]; then
  run_ipfs_pid=''
  (
    export IPFS_PATH="${OD}/ipfs_repo";
    [ -e ${OD}/ipfs_repo/config ] && echo "ipfs repo ready" || ${OD}/bin/ipfs init && \
    rm -f ${OD}/ipfs_repo/api ${OD}/ipfs_repo/repo.lock && ./run_ipfs.py daemon &
  )

  sed "s|__OPTRACT_INSTALL__|${OD}|g" ./dapps/config.json.dist > ./dapps/config.json && \
  rm -fr ${OD}/node_modules && ${OD}/bin/asar extract ${OD}/node_modules.asar ${OD}/node_modules && \
  launch 0.01 && ${OD}/bin/node ${OD}/lib/daemon.js && ./run_ipfs.py kill || ./run_ipfs.py kill;
  exit 0;
fi
