#!/bin/bash

OD=`pwd`;
MO=$1;

if [ ${MO:-daemon} == "console" ]; then
   exec $OD/bin/node $OD/lib/console.js;
fi

(
  export IPFS_PATH="${OD}/ipfs_repo";
  [ -e ${OD}/ipfs_repo/config ] && echo "ipfs repo ready" || ${OD}/bin/ipfs init && \
  ${OD}/bin/ipfs daemon --routing=dhtclient &
)

sed "s|__OPTRACT_INSTALL__|${OD}|g" ./dapps/config.json.dist > ./dapps/config.json && \
 rm -fr ${OD}/node_modules && ${OD}/bin/asar extract ${OD}/node_modules.asar ${OD}/node_modules && \
 ${OD}/bin/node ${OD}/lib/daemon.js && pkill -15 ipfs;
